#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_user:
  path: /user/api_user
  controller: App\Controller\UserController::api_user

api_login:
  path: /api/login
  controller: App\Controller\ApiLoginController::login
  methods: POST

api_register:
  path: /api/register
  controller: App\Controller\ApiRegisterController::register
  methods: POST

app_logout:
  path: /logout
  controller: App\Controller\ApiLoginController::logout
  methods: GET