#index:
#    path: /
#    controller: App\Controller\DefaultController::index

get_users:
  path: /api/get_users
  controller: App\Controller\ApiUserController::get_users
  methods: GET

api_login:
  path: /api/login
  controller: App\Controller\ApiLoginController::login
  methods: POST

api_register:
  path: /api/register
  controller: App\Controller\ApiRegisterController::register
  methods: POST

api_update:
  path: /api/update/{id}
  controller: App\Controller\ApiUpdateController::update
  methods: POST

api_delete:
  path: /api/delete/{id}
  controller: App\Controller\ApiDeleteUserController::delete
  methods: DELETE

app_logout:
  path: /logout
  controller: App\Controller\ApiLoginController::logout
  methods: GET

#api_login_check:
#  path: /api/login_check