version: "3.6"
services:
  mariadb:
    image: mariadb:10.3.34
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: users_api_db
      MARIADB_ROOT_PASSWORD: PslmSD15Q4
      MARIADB_PASSWORD: k6avrXKjfJ
      MARIADB_USER: db_user
    ports:
      - "13307:3306"
    networks:
      - users_api_network

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../:/var/www/users_api
    depends_on:
      - mariadb
    privileged: true
    networks:
      - users_api_network

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/users_api
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - users_api_network

networks:
  users_api_network:
    driver: bridge